- name: Bootstrap EC2 (Install Python)
  hosts: web
  gather_facts: false
  become: yes
  tasks:
    - name: Ensure Python 3.8 is installed
      raw: |
        amazon-linux-extras enable python3.8
        yum install -y python3
      args:
        executable: /bin/bash

- name: Configure EC2
  hosts: web
  become: true
  gather_facts: true

  tasks:
    - name: Update packages
      ansible.builtin.yum:
        name: "*"
        state: latest
    
    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: true

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    
    - name: Install Docker Python SDK
      ansible.builtin.yum: 
        name: python3-pip
        state: present
    
    - name: Install Docker SDK for Python
      pip:
       executable: pip3
       name:
         - docker
         - "requests<2.32"
         - "urllib3<2"
       state: forcereinstall

    - name: Run nginx container
      community.docker.docker_container:
        name: nginx_test
        image: nginx
        state: started
        ports:
          - "80:80"

    - name: Verify nginx is up
      ansible.builtin.uri:
        url: http://{{ ansible_host }}:80
