apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: cicd-lab:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - "-nginx.scrape-uri=http://localhost:80/stub_status"
          ports:
            - name: metrics
              containerPort: 9113

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config