resources:
  - ../../base
  - configmap.yaml
  - nginx-servicemonitor.yaml

namespace: dev

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENV
            value: dev