name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - run: pip install -r requirements.txt
        - run: python -c "print('Test passed')"
    
    build:
      needs: ci
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: docker build -t cicd-lab:${{ github.sha }} .
    
    terraform-plan:
      needs: build
      runs-on: ubuntu-latest

      outputs:
          exitcode: ${{ steps.plan.outputs.exitcode }}

      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: arn:aws:iam::542525596293:role/terraform-execution-role
            aws-region: us-east-1

        - uses: actions/checkout@v3

        - name: List files (debug)
          run: ls -R

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_wrapper: false
        
        - name: Terraform init
          run: terraform init
          working-directory: ./terraform
        
        - name: Save plan
          id: plan
          working-directory: ./terraform
          shell: bash
          run: | 
            set +e
            terraform plan -detailed-exitcode -out=tfplan
            EXIT_CODE=$?
            set -e

            echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT

            if [ $EXIT_CODE -eq 1 ]; then
              echo "Terraform plan failed"
              exit 1
            fi
        
        - name: Dump all outputs
          run: |
            echo "Plan exit code (step output): ${{ steps.plan.outputs.exitcode }}"
            echo "Raw GITHUB_OUTPUT contents:"
            cat $GITHUB_OUTPUT

        - name: Debug exit code
          run: echo "Exit code was ${{ steps.plan.outputs.exitcode }}"
        
        - name: Upload plan
          uses: actions/upload-artifact@v4
          with:
            name: tfplan
            path: terraform/tfplan 

    terraform-apply:
      needs: terraform-plan
      runs-on: ubuntu-latest
      environment: prod
      if: needs.terraform-plan.outputs.exitcode == '2'
      
      steps:
        - name: Verify received exit code
          run: |
            echo "Received exitcode from terraform-plan job: ${{ needs.terraform-plan.outputs.exitcode }}"

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: arn:aws:iam::542525596293:role/terraform-execution-role
            aws-region: us-east-1

        - name: Check identity after credentials configuration
          run: aws sts get-caller-identity

        - uses: actions/checkout@v3

        - name: List files (debug)
          run: ls -R
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Download plan
          uses: actions/download-artifact@v4
          with:
            name: tfplan
            path: terraform
        
        - name: Terraform init
          run: terraform init
          working-directory: ./terraform
        
        - name: Terraform apply
          run: terraform apply -auto-approve tfplan
          working-directory: ./terraform
        
        - name: Get EC2 IP
          id: terraform_output
          run: |
            cd terraform
            echo "EC2_IP=$(terraform output -raw public_ip)"
            echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519

        - name: Update inventory
          run: |
            sed -i "s/EC2_IP_PLACEHOLDER/$EC2_IP/" ansible/inventory.ini
            cat ansible/inventory.ini

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Setup Python venv for Ansible
          shell: bash
          run: |
            python -m venv .venv
            . .venv/bin/activate

            python -m pip install --upgrade pip setuptools wheel
            
            pip install "ansible-core==2.14.10" \
                        "urllib3<2" \
                        "requests<2.32"

            python --version
            ansible --version
        
        - name: Disable host key checking
          run: |
            echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            cat ~/.ssh/config

        - name: Install Docker collection
          run: |
            source .venv/bin/activate
            ansible-galaxy collection install community.docker

        - name: List installed collections
          run: |
            source .venv/bin/activate
            ansible-galaxy collection list

        - name: Run Ansible
          run: |
            source .venv/bin/activate
            
            .venv/bin/ansible-playbook -i ansible/inventory.ini ansible/playbook.yml -vvv
